# Generated by Django 4.2 on 2025-02-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
